spring:
  datasource:
    url: ${DBMS_CONNECTION}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret-key: ${SECRET_KEY}
  valid-duration: 240
  refreshable-duration: 140

admin:
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}

  server:
    port: 8080
    ssl:
      key-store-type: PKCS12
      key-store: classpath:producerworkbench.p12
      key-store-password:  ${KEY_STORE_PASSWORD}
      key-alias: ${KEY_ALIAS}

spotify:
  client-id: ${SPOTIFY_CLIENT_ID}
  client-secret: ${SPOTIFY_CLIENT_SECRET}