spring:
  datasource:
    url: ${DBMS_CONNECTION}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: my-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: "com.fpt.producerworkbench.dto.event" # hoặc "*" để cho phép tất cả các package
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  data:
    redis:
      host: localhost
      port: 6379
      password: ""  # Nếu không có mật khẩu

  jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: yyyy-MM-dd

jwt:
  secret-key: ${SECRET_KEY}
  valid-duration: 240
  refreshable-duration: 140

admin:
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}

  server:
    port: 8080
    ssl:
      key-store-type: PKCS12
      key-store: classpath:producerworkbench.p12
      key-store-password:  ${KEY_STORE_PASSWORD}
      key-alias: ${KEY_ALIAS}
    tomcat:
      uri-encoding: UTF-8
    servlet:
      encoding:
        charset: UTF-8
        enabled: true
        force: true



spotify:
  client-id: ${SPOTIFY_CLIENT_ID}
  client-secret: ${SPOTIFY_CLIENT_SECRET}

signnow:
  base-url: ${SN_BASE_URL:https://api-eval.signnow.com}
  client-id: ${SN_CLIENT_ID}
  client-secret: ${SN_CLIENT_SECRET}
  auth:
    username: ${SN_USERNAME}
    password: ${SN_PASSWORD}
  http:
    connect-timeout-ms: ${SN_HTTP_CONNECT_TIMEOUT_MS:10000}
    read-timeout-ms: ${SN_HTTP_READ_TIMEOUT_MS:20000}


pwb:
  contract:
    template: classpath:templates/hop-dong-san-xuat-am-nhac.pdf
    font: classpath:/templates/NotoSerif-Regular.ttf

storage:
  base-dir: ${STORAGE_BASE_DIR:/var/pwb-files}

logging:
  charset:
    console: UTF-8
    file: UTF-8