spring:
  datasource:
    url: ${DBMS_CONNECTION}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: my-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: "com.fpt.producerworkbench.dto.event"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  data:
    redis:
      host: localhost
      port: 6379
      password: "" 

  jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: yyyy-MM-dd

jwt:
  secret-key: ${SECRET_KEY}
  valid-duration: 240
  refreshable-duration: 140

admin:
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}

customer:
  username: ${CUSTOMER_USERNAME}
  password: ${CUSTOMER_PASSWORD}
  
producer:
  username: ${PRODUCER_USERNAME}
  password: ${PRODUCER_PASSWORD}

spotify:
  client-id: ${SPOTIFY_CLIENT_ID}
  client-secret: ${SPOTIFY_CLIENT_SECRET}

signnow:
  base-url: ${SN_BASE_URL:https://api.signnow.com}
  client-id: ${SN_CLIENT_ID}
  client-secret: ${SN_CLIENT_SECRET}
  auth:
    username: ${SN_USERNAME}
    password: ${SN_PASSWORD}
  http:
    connect-timeout-ms: ${SN_HTTP_CONNECT_TIMEOUT_MS:10000}
    read-timeout-ms: ${SN_HTTP_READ_TIMEOUT_MS:120000}


pwb:
  contract:
    template: classpath:templates/hop-dong-san-xuat-am-nhac.pdf
    font: classpath:/templates/NotoSerif-Regular.ttf

storage:
  base-dir: ${STORAGE_BASE_DIR:/var/pwb-files}
  
cloudfront:
  domain: ${CLOUDFRONT_DOMAIN}

aws:
  region: ${AWS_REGION}
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}
  s3:
    bucket-name: ${S3_BUCKET_NAME}

logging:
  charset:
    console: UTF-8
    file: UTF-8
  
outbound:
  identity:
    client-id: ${OUTBOUND_CLIENT_ID}
    client-secret: ${OUTBOUND_CLIENT_SECRET}
    redirect-uri: ${OUTBOUND_REDIRECT_URI}

cors:
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:5173,http://localhost:8080}

payos:
  client-id: ${PAYOS_CLIENT_ID}
  api-key: ${PAYOS_API_KEY}
  checksum-key: ${PAYOS_CHECKSUM_KEY}
  return-url: ${PAYOS_RETURN_URL}
  cancel-url: ${PAYOS_CANCEL_URL}
